version: '3.2'

services:
  ussd-tr:
    build: .
    image: vincentminde/trader:1.0.0
    working_dir: /home/app
    environment:
      - NODE_ENV=production
    command: npx ng serve api
    #command: ls
    restart: always
    environment:
        - PORT=3000
    volumes:
      - type: bind
        source: ./apps
        target: /home/app/apps
      - type: bind
        source: ./libs
        target: /home/app/libs
  # database:
  #   image: postgres:10.12
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ussd-tr-db-data:/var/lib/postgresql/data
volumes:
  ussd-tr-db-data:
    driver: local