version: '3.2'

services:
  trainer:
    container_name: trainer
    build: .
    image: ussd/trader:1.0.0
    working_dir: /home/app
    environment:
      - NODE_ENV=production
      - MODE=train
      - INSTRUMENT=EUR_USD
    command: npx ng serve api
    restart: always
    volumes:
      - type: bind
        source: ./apps
        target: /home/app/apps
      - type: bind
        source: ./libs
        target: /home/app/libs
      - type: bind
        source: ./models
        target: /home/app/models
  trader:
    container_name: trader
    build: .
    image: ussd/trader:1.0.0
    working_dir: /home/app
    environment:
      - NODE_ENV=production
      - MODE=trade
      - INSTRUMENT=EUR_USD
    command: npx ng serve api
    restart: always
    volumes:
      - type: bind
        source: ./apps
        target: /home/app/apps
      - type: bind
        source: ./libs
        target: /home/app/libs
      - type: bind
        source: ./models
        target: /home/app/models
  database:
    container_name: trader-db
    image: postgres:10.12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trader
    volumes:
      - ussd-tr-db-data:/var/lib/postgresql/data
volumes:
  ussd-tr-db-data:
    driver: local